### ISSUE TITLE
missing tutorial

### ISSUE THREAD

**Issue by this-oliver** [ranimkhojah/batata#1]
**batata isn't moving.**

env: https://ranimkhojah.github.io/batata/

I keep telling batata to move but he doesn't listen to me at all :(

I've used the following phrases:
- "move to the right"
- "move forward"
- "go"
- "go pls"

**Comment by ranimkhojah** [comment]
@olivermanzi supported browsers are Google Chrome and Firefox Nightly :) will update the instructions 👍 
also, you can use more "natural" language with Batata! e.g. go somewhere next to the cabinet or take a look inside it
